config/routes.rb
#encoding: utf-8
#include Rails.application.routes.url_helpers #在console中调用orders_path等
Shopqi::Application.routes.draw do

  mount Doorkeeper::Engine => '/oauth'

  namespace :api, defaults: {format: 'json'} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do
      get '/shop'           , to: "shops#show"
      post '/themes/install', to: 'themes#install'
      get '/products'       , to: "products#index"
      get '/products/:id'   , to: "products#show"
      put '/variants/:id'   , to: "product_variants#update"
      get '/orders'         , to: "orders#index"
      get '/orders/:id'     , to: "orders#show"
      post '/webhooks'      , to: "webhooks#create"
    end
  end

  constraints(Domain::Wiki) do # 帮助文档
    devise_for :admin_users, ActiveAdmin::Devise.config
    scope module: :wiki do
      get '/'                         , to: 'wiki_pages#index'           , as: :wiki_pages_index
      get '/active_admin'             , to: redirect('/')
      resources :wiki_pages           , only:[:new                       , :create]
      get '/pages'                    , to: 'wiki_pages#pages'           , as: :wiki_pages_all
      match '/search'                 , to: 'wiki_pages#search'
      get '/history/:name'            , to: 'wiki_pages#history'
      get '/robots.txt'               , to: 'wiki_pages#robots'
      get '/:name'                    , to: 'wiki_pages#show'
      post '/destroy/:name'           , to: 'wiki_pages#destroy'
      get '/edit/:name'               , to: 'wiki_pages#edit'
      post '/compare/:name'           , to: 'wiki_pages#compare'
      get '/compare/:name/:sha1/:sha2', to: 'wiki_pages#compare_versions'
      post '/revert/:name/:sha1/:sha2', to: 'wiki_pages#revert'
      get '/:name/:sha'               , to: 'wiki_pages#show'
      post '/update'                  , to: 'wiki_pages#update'          , as: :update_page
      post '/preview'                 , to: 'wiki_pages#preview'
    end
  end

  constraints(Domain::Theme) do # 主题商店
    scope module: :theme do
      get '/', to: 'themes#index', as: :theme_index
      scope "/themes" do
        get '/login'                                , to: 'themes#login'       , as: :theme_login
        get '/logout'                               , to: 'themes#logout'      , as: :theme_logout
        get '/get_shop'                             , to: 'themes#get_shop'    , as: :theme_get_shop
        post '/login/authenticate'                  , to: 'themes#authenticate', as: :theme_authenticate
        get '/filter'                               , to: 'themes#filter'
        get '/:handle/styles/:style_handle'         , to: 'themes#show'        , as: :theme
        get '/:handle/styles/:style_handle/download', to: 'themes#download'    , as: :theme_download
        match '/:handle/styles/:style_handle/apply' , to: 'themes#apply'
      end
      get '/robots.txt'                             , to: 'themes#robots'

      begin 'client' # 作为oauth client
        get '/callback', to: redirect('/themes/get_shop')
      end
    end
  end

  ##### 商店及后台管理通用 #####
  match '/district/:id', to: 'district#list' # 地区选择(创建订单页面)
  scope module: :shop do
    match '/s/files/:id/theme/:theme_id/assets/:file.:format'            , to: 'shops#asset', file: /.+/
    match '/s/files/development/:id/theme/:theme_id/assets/:file.:format', to: 'shops#asset', file: /.+/ #开发中使用
    match '/s/files/test/:id/theme/:theme_id/assets/:file.:format'       , to: 'shops#asset', file: /.+/ #测试中使用
  end

  constraints(Domain::Shopqi) do
    scope module: :shopqi do # 官网
      root to: "home#page"
      get '/faq'       , to: 'home#faq'     , as: :faq
      get '/links'     , to: 'home#links'   , as: :home_links
      get '/about'     , to: 'home#about'   , as: :about
      scope "/tour" do # 功能演示
        get '/'        , to: 'home#tour'    , as: :tour_intro
        get '/store'   , to: 'home#store'   , as: :tour_store
        get '/design'  , to: 'home#design'  , as: :tour_design
        get '/security', to: 'home#security', as: :tour_security
        get '/features', to: 'home#features', as: :tour_features
      end
      get '/agreement', to: 'home#agreement'            , as: :agreement
      get '/signup'   , to: redirect('/services/signup')
      get '/login'    , to: 'home#login'
      scope "/services/signup" do
        # :confirmations, :omniauth_callbacks, :passwords, :registrations, :sessions, :unlocks
        devise_for :user, skip: [:sessions, :confirmations, :passwords], skip_helpers: true
        devise_scope :user do
          get '/new/professional'  , to: 'registrations#new'                         , as: :services_signup
          get "/new/:plan"         , to: "registrations#new"                         , as: :signup
          get "/check_availability", to: "registrations#check_availability"
          post "/user"             , to: "registrations#create"                      , as: :signup_user
          post "/verify_code"      , to: "registrations#verify_code" # 获取手机校验码
        end
      end
      get '/robots.txt', to: 'home#robots'
    end

    #官网后台管理
    ActiveAdmin.routes(self)
    authenticate :admin_user do # 管理员权限
      mount Resque::Server.new, at: "/resque" # 查看后台任务执行情况
    end

    devise_for :admin_users, ActiveAdmin::Devise.config
  end

  constraints(Domain::Store) do

    devise_for :user, skip: :registrations, controllers: {sessions: "admin/sessions"} # 登录

    scope module: :shop do # 前台商店
      scope '/account' do
        devise_for :customer, only: :passwords
        devise_scope :customer do
          get '/login'                     , to: 'sessions#new'        , as: :new_customer_session
          post '/login'                    , to: 'sessions#create'
          get '/logout'                    , to: 'sessions#destroy'
          get '/signup'                    , to: 'registrations#new'   , as: :new_customer_registration
          post '/customer'                 , to: 'registrations#create', as: :customer_registration
        end
        get '/orders/:token'               , to: 'account#show_order', as: :account_show_order
        get '/index'                       , to: 'account#index'     , as: :customer_root
        get '/'                            , to: 'account#index'
        resources :customer_addresses      , path: '/addresses'
      end
      match '/'                                             , to: 'shops#show'
      match '/password'                                     , to: 'shops#password'
      get   '/unavailable'                                  , to: 'shops#unavailable'
      get '/themes'                                         , to: 'shops#themes'        , as: :shop_themes_tip
      get '/search'                                         , to: 'search#show'
      get '/products/:handle'                               , to: 'products#show'       , as: :product_show
      get '/collections/:collection_handle/products/:handle', to: 'products#show'       , as: :collection_product_show
      get '/collections'                                    , to: 'collections#index'
      get '/products'                                       , to: 'collections#index'   , as: :shop_products
      get '/collections/all'                                , to: 'collections#show_all'
      get '/collections/:handle/products'                   , to: 'collections#show'
      get '/collections/:handle'                            , to: 'collections#show_with_types_or_vendors' , constraints: { handle: /types|vendors/ }
      get '/collections/:handle/:tags'                      , to: 'collections#show_with_tag'
      get '/collections/:handle'                            , to: 'collections#show'
      get '/pages/:handle'                                  , to: 'pages#show'
      post '/cart/add'                                      , to: 'cart#add'
      get '/cart'                                           , to: 'cart#show'
      post '/cart'                                          , to: 'cart#update'
      get '/cart/change/:variant_id'                        , to: 'cart#change'
      post '/cart/change'                                   , to: 'cart#change'
      post '/cart/clear'                                    , to: 'cart#clear'
      begin 'checkout' # 结算
        get '/carts/:cart_token'                            , to: 'order#new'
        get '/carts/:cart_token/shipping_rates/:code'       , to: 'order#shipping_rates'
        get '/carts/:cart_token/get_address'                , to: 'order#get_address'       , as: :get_address
        post '/carts/:cart_token/apply_discount'            , to: 'order#apply_discount'
        post '/carts/:cart_token'                           , to: 'order#create'
        post '/orders/notify'                               , to: 'order#notify'            , as: :notify_order
        get '/orders/done'                                  , to: 'order#done'              , as: :done_order
        match '/orders/tenpay_notify'                       , to: 'order#tenpay_notify'     , as: :tenpay_notify_order
        get '/orders/tenpay_done/:token'                    , to: 'order#tenpay_done'       , as: :tenpay_done_order
        get '/orders/:token'                                , to: 'order#show'              , as: :shop_order
      end
      get '/blogs/:handle'                                  , to: 'blogs#show'
      get '/blogs/:handle/:id'                              , to: 'articles#show'
      match '/blogs/:handle/:id/comments'                   , to: 'articles#add_comment'
      post '/contact'                                       , to: 'contact#create'
      get '/robots.txt'                                     , to: 'shops#robots'
    end

    scope module: :admin do # 用户后台管理(无 /admin 前缀)
      post '/kindeditor/upload_image', to: 'kindeditor#upload_image'
    end

    scope "/admin", module: :admin do # 用户后台管理

app/controllers/admin/products_controller.rb
#encoding: utf-8
class Admin::ProductsController < Admin::AppController
  prepend_before_filter :authenticate_user!
  layout 'admin'
  expose(:shop) { current_user.shop }
  expose(:products) do
    if params[:search]
      shop.products.metasearch(params[:search]).all
    else
      shop.products
    end
  end
  expose(:product)
  expose(:product_json) do
    product.to_json({
      include: { options: { methods: [:value, :first, :last], except: [ :created_at, :updated_at ] },photos: {methods: :icon} },
      methods: [:tags_text, :custom_collection_ids],
      except: [ :created_at, :updated_at ]
    })
  end
  expose(:variants) { product.variants }
  expose(:variants_json) { variants.to_json(except: [ :position, :created_at, :updated_at ]) }
  #expose(:variant) { variants.new }
  expose(:types) { shop.types }
  expose(:types_options) { types.map {|t| [t.name, t.name]} }
  expose(:vendors) { shop.vendors }
  expose(:vendors_options) { vendors.map {|t| [t.name, t.name]} }
  expose(:inventory_managements) { KeyValues::Product::Inventory::Manage.options }
  expose(:inventory_policies) { KeyValues::Product::Inventory::Policy.all }
  expose(:options) { KeyValues::Product::Option.all.map {|t| [t.name, t.name]} }
  expose(:tags) { shop.tags.previou_used(1) }
  expose(:custom_collections) { shop.custom_collections }
  expose(:publish_states) { KeyValues::PublishState.options }
  expose(:photos){ product.photos }
  expose(:photo){ Photo.new }
  expose(:current_sku_size){ shop.variants.size }
  expose(:shop_sku_size){ shop.plan_type.skus }

  def index
    @products_json = products.to_json({include: [:variants, :options], except: [:created_at, :updated_at],methods:[:index_photo]})
  end

  def inventory
    @product_variants = ProductVariant.joins(:product).where(inventory_management: 'shopqi', product: {shop_id: shop.id})
  end

  def new
    #保证至少有一个款式
    product.variants.build  if product.variants.empty?
  end

  def create
    images = params[:product][:images] || []
    images.each_with_index do |i,pos|
      product.photos.build(product_image: i,position: pos)
    end
    #保存商品图片
    if product.save
      shop.activities.log product,'new',current_user
      redirect_to product_path(product, new_product: true), notice: "新增商品成功!"
    else
      render action: :new
    end
  end

  def destroy
    product.destroy
    redirect_to products_path
  end

  def update
    product.save
    product.options.reject! {|option| option.destroyed?} #rails bug：使用_destroy标记删除后，需要reload后，删除集合中的元素才消失，而reload后value值将被置空
    shop.activities.log product,'edit',current_user
    render json: product_json
  end

  # 批量修改
  def set
    operation = params[:operation].to_sym
    ids = params[:products]
    if [:publish, :unpublish].include? operation #可见性
      products.where(id:ids).update_all published: (operation == :publish)
      products.where(id:ids).map{|product|log_published(product)}
    elsif operation == :destroy #删除
      products.find(ids).map(&:destroy)
    else #加入集合
      #'add_to_collection-1'
      collection_id = operation.to_s.sub 'add_to_collection-', ''
      collection = shop.custom_collections.find(collection_id)
      ids.each do |id|
        unless collection.collection_products.exists?(product_id: id)
          collection.collection_products.build product_id: id
        end
      end
      collection.save
    end
    render nothing: true
  end

  # 复制
  def duplicate
    new_product = product.dup
    new_product.variants = product.variants.map(&:dup)
    new_product.options = product.options.map(&:dup).each{|o| o.position = nil } # Fixed: #159 position不为空导致排序报错
    new_product.custom_collection_products = product.custom_collection_products.map(&:dup)
    new_product.tags_text = product.tags_text
    new_product.update_attributes title: params[:new_title]
    render json: {id: new_product.id}
  end

  #更新可见性
  def update_published
    flash.now[:notice] = I18n.t("flash.actions.update.notice")
    product.save
    log_published(product)
    render template: "shared/msg"
  end

  protected

  def log_published(product)
    handle = product.published ? 'published' : 'hidden'
    shop.activities.log product,handle,current_user
  end
end

app/controllers/api/v1/products_controller.rb
# encoding: utf-8
module Api::V1
  class ProductsController < AppController
    doorkeeper_for :index, :show, scopes: [:read_products, :write_products], unless: lambda { @api_client }

    def index
      @products = shop.products.page(page).per(per_page)
    end

    def show
      @product = shop.products.find(params[:id])
    end

  end
end

app/views/admin/products/_collection.html.haml
%li.product-edit-collection
  =check_box_tag 'product[custom_collection_ids][]', collection.id, product.custom_collections.include?(collection) || (collection.handle == 'frontpage' and collection.products.size.zero?), id: "collection_#{collection.id}"
  %label(for="collection_#{collection.id}")=collection.title

app/views/admin/products/_product.html.haml
%tr(class="product row#{cycle(:odd, :even)}")
  %td(style="padding-right: 5px; vertical-align: middle;")
    %input#checkbox-38663892.selector(name="products[]" type="checkbox" value="38663892")/
  %td.list-image(style="text-align: center ! important;")
    %label(for="checkbox-38663892")=image_tag 'other/no-image-thumb.gif'
  %td(style="padding-left: 3px; vertical-align: middle;")
    %p=link_to product.title, product_path(product), title: "处理:#{product.title}"
    %p.list-product-type=product.product_type
    %p.list-vendor=product.vendor
  %td.list-variants
    .expand-collapse-info.notification.hide
      %p(style="position: absolute; top: 11px")
        %a.expand(href="#")=image_tag 'admin/icons/arrow_right_small.png'
        %a.collapse.hide(href="#")=image_tag 'admin/icons/arrow_down_small.png'
    %ul#variant-list-38663892.variant-list.nobull.product-list-option-1
      -product.variants.each do |variant|
        %li.variant-list-item
          -product.options.each_with_index do |option, index|
            %p.note(style="font-size: 9px; line-height: 11px; margin: 0")=variant.attributes["option#{index+1}"]
          %span.large(style="font-size: 14px;line-height: 25px")=variant.inventory_quantity
          %br/
          .variant-tip.newtip.hide
            .default
              .content=variant.sku ? variant.sku : "没有SKU"
  %td.list-total(style="text-align: center; vertical-align: middle;")
    %span(style="font-size: 18px")=product.variants.map(&:inventory_quantity).sum

app/views/admin/products/_upload_photos.html.haml
-if product.photos.blank?
  #upload-product-image.c
    %a.show-upload-link
      =image_tag 'other/no_product_image.gif',class: 'sb', alt: 'No_product_image'
-else
  %ul#image_list.clearfix(url="#{sort_product_photos_path(product)}")
    -product.photos.each_with_index do |photo,index|
      %li(id="photo_#{photo.id}")
        .product_image
          =link_to image_tag(photo.small, class: 'closure-lightbox'), photo.large
        = link_to image_tag('admin/icons/trash.gif'), product_photo_path(product,photo), method: :delete, title: '删除它', class: 'image-delete',remote: true, data: { confirm: '您确定要删除此张图片吗?' }
        =image_tag 'admin/icons/drag_handle.gif', :alt => '拖动排序', :class => "image-drag"
        -if index == 0
          .featured

app/views/admin/products/show.html.haml
-use_kindeditor

%h2#product_title= link_to product.title, "/products/#{product.handle}", title: '在网店中查看此页面', target: '_blank'
#action-links
  %ul
    %li.no-icon
      %a.edit-btn(href="#") 修改
    %li.no-icon
      %a.dup-btn(href="#") 复制此商品
    %li.no-icon
      = link_to image_tag('admin/icons/trash.gif'), product_path(product), method: :delete, title: '删除它', class: :del, data: {  confirm: '您确定要删除此商品吗?' }

#duplicate-product.group.hide
  .group-fields
    %label.sb(for="duplicate_product_title" style="display:block;") 请输入新商品的标题
    %input#duplicate_product_title(name="product[title]" size="30" type="text")
  .group-actions
    %input#duplicate_product_submit.btn(name="commit" type="submit" value="复制商品")
      或者
      %a.cancel(href="#") 取消

=form_for product, url: duplicate_product_path(product), method: :post, html: {id: 'new_product'} do |f|
  =hidden_field_tag 'new_product[title]'
.st
  #product-summary
    - if params[:new_product]
      #create-more-products.box2.message.sb
        %h3
          还有商品?
          =link_to '增加另一个商品', new_product_path
    %table(cellpadding="0" cellspacing="0" style="width:100%")
      %tr
        %td#product-details
          #product

          #product-edit.hide
        %td#product-right-col(style="width: 275px; padding: 0 0 0 10px")
          %h3.section-header(style="margin-bottom: 0") 商品图片
          #product-image-area.group
            #image-show-area=render partial:'upload_photos',locals:{product:product}
            #upload-label.action-container
              .action-link.c(style="border-bottom: none")
                %span
                  %a.show-upload-link
                    %span.plus +
                    上传图片
            .clearfix
          #upload-area.hide
            %p#status.hide
              =image_tag 'admin/icons/trash.gif', alt: '删除'
              =image_tag 'spinner.gif',class: 'fr st pad', alt: 'Spinner'
            =form_for [product,photo], html: { multipart: true },remote: true do |p|
              %h4.st 上传图片
              %p.note 允许上传文件类型( .gif, .jpg, .jpeg, .png)
              %p#file-input.st.sb
                =p.file_field :product_image,id:"add-file",onchange: "$('#new_photo').submit();"
          .sst.pl
            %h3 商品可见性
            %p.sb.note
              如果你不需要此商品显示在您的商店中，您可以设置它的可见性为
              %em 隐藏
              \.
            =form_for product, url: update_published_product_path(product), remote: true, html: {id: 'product_publicshed_form'} do |f|
              =f.select :published, publish_states, {}, style: "width: 120px; font-size: 13px", onchange: "$('#product_publicshed_form').submit();"
  #variant-inventory.pgroup
    %h3.sb 库存
    %form#batch-form(action='#' onsumbit='return false')
      #variant-options.note(style="margin:10px 0")
      %table#product-controls.hide(cellpadding="0" cellspacing="0")
        %tr
          %td(style="text-align:left;")
            %select#product-select(name="operation")
            %span#new-value.hide
              %input(type="text" name="new_value" size="10" value="")
              %input(type="submit" value="保存")
              =w('or')
              %a.cancel(href="#")=w('cancel')
          %td(style="text-align:right; color: #333")
            %span#product-count.note &nbsp;
    %table#product-table.data(style="font-size: 12px;" cellpadding="0" cellspacing="0")
      %tr#row-head
    %ul#variants-list
    #new-variant-link.action-row
      .action-link
        %p
          %a(href="#")
            %span.plus +
            新增款式
  #new-variant.hide

%script(id="show-product-item" type="text/x-handlebars-template")
  #product-body.textile.ssb
    %table.data.table-wrapper(cellpadding="0" cellspacing="0")
      %tr
        %th.section-header 描述
      %tr
        %td(style="padding: 10px; font-size: 12px")
          %p {{{body_html}}}
  #product-options.section
    %table.data(cellpadding="0" cellspacing="0")
      %tbody
        %tr
          %th.section-header(colspan="2") 属性
        %tr
          %td.cell-title
            %strong 商品类型:
          %td.middle.cell-data
            %span#product-type.small {{{product_type}}}
        %tr
          %td.cell-title
            %strong 商品生产商:
          %td.middle.cell-data
            %span#product-vendor.small {{{vendor}}}
        %tr
          %td.cell-title
            %strong 库存:
          %td.middle.cell-data &infin;
      %tbody#product-options-list
  #tagging.section
    #product-tags
      %table.data(cellpadding="0" cellspacing="0")
        %tr
          %th.section-header 标签
        %tr
          %td(style="padding: 15px 10px;")
            %ul.tag-list
              {{#each tags}}
              %li
                %span.list-box.active-tag {{this}}
              {{/each}}
            {{#unless tags}}
            %p 您还没有添加任何标签到此商品.
            {{/unless}}
  .section
    #product-collections
      %table.data(cellpadding="0" cellspacing="0")
        %tr
          %th.section-header 集合
        %tr
          %td(style="padding: 15px 10px 0 10px;")
            {{#if collections_empty}}
            %p 此商品不属于任何集合.
            {{else}}
            %p 此商品属于以下集合:
            {{/if}}
            %ul.product-collection-list.pgroup
              {{#each collections}}
              %li
                %a(href="/admin/custom_collections/{{id}}") {{title}}
              {{/each}}

%script(id="edit-product-item" type="text/x-handlebars-template")
  =form_for product, class: :edit_product, html: {id: 'product-detail-form', onsubmit: 'return false;'} do |f|
    #product-body-edit.sb
      .section-header
        %strong 修改此商品
      .padding
        #errors_for_product
        %dl(style="background: none; margin-bottom: 0")
          %dt=f.label :title, nil, style: "margin: 0", for: :title
          %dd=text_field_tag :title, '{{{title}}}', class: [:big, :sb]
          %dt#edit-handle-label
            固定链接
            %span.note
              (
              %a(href="#{wiki_url_with_port}/Handle" target="_blank") 这是什么?
              )
          %dd#edit-handle.ssb
            %span.note==#{shop.primary_domain.url}/products/
            =text_field_tag :handle, '{{{handle}}}', style: 'width: 160px'
          %dt=f.label :body_html
          %dd=text_area_tag :body_html, '{{body_html}}', id: 'kindeditor', style: "width: 895px; height: 200px;"
    #product-options-edit.section
      %table#product-properties.data.sb(cellpadding="0" cellspacing="0")
        %tr
          %th.section-header(colspan="2") 属性
        %tr
          %td.cell-title
            %strong 商品类型:
          %td
            %select#product-type-select
              =options_for_select types_options
            #new_product_type.st.sb.hide
              %h4.note 新的商品类型
              =text_field_tag :product_type, '{{{product_type}}}'
        %tr
          %td.cell-title
            %strong 商品生产商:
          %td
            %select#product-vendor-select
              =options_for_select vendors_options
            #new_product_vendor.st.sb.hide
              %h4.note 新的商品生产商:
              =text_field_tag :vendor, '{{{vendor}}}'
        %tr#add-option-bt.hide
          %td.cell-title
            %a.add-option(href="#") 新增另一个选项
            %br
            %span.note 例如. 颜色, 大小
          %td &nbsp;
    #product-edit-tags
      .section-header 标签
      %dl.padding(style="background: none; margin: 0;")
        %dd#multi-options
          %p.note.sb 标签之间以逗号分隔.
          =text_field_tag :tags_text, '{{{tags_text}}}', size: 50, id: :product_tags_text
        %dd.sst
          %p.note(style="clear: both") 最近使用过的标签，单击增加.
          %ul#tag-list.tag-list
            -tags.each do |tag|
              %li
                %a(href="#")=tag.name
          .cl
    #product-edit-collections
      .section-header 集合
      %p.note(style="margin: 10px 0px 5px 5px;") 选择此商品所属的自定义集合:
      %ul.nobull.pgroup.clearfix=render partial: "collection", collection: custom_collections
    .group-actions
      =f.submit "保存", id:"update-options", class: :btn
      =w('or')
      %a.cancel(href="#")=w('cancel')
%script(id="row-head-item" type="text/x-handlebars-template")
  %th(class="checkbox-cell")
    %input#select-all(type="checkbox")
  {{#each_with_index options}}
  %th.option-title(id="option-header-{{index_plus}}" option-id="{{item.attributes.id}}" class="option-{{index_plus}}" style="width:15%;")
    {{#unless item.attributes.first}}
    %span.mover.hide(dir="-1" style="position: absolute; margin-left: -15px;")
      %a(href="#" style="color: #666; text-decoration:none" title="移到左边") ←
    {{/unless}}
    {{item.attributes.name}}
    {{#unless item.attributes.last}}
    %span.mover.hide(dir="1")
      %a(href="#" style="color: #666; text-decoration:none" title="移到右边") →
    {{/unless}}
  {{/each_with_index}}
  %th(style="min-width: 150px") SKU
  %th.price-cell(style="width: 90px;")
    价格
    %span.note 元
  %th.qty-cell(style="width:50px") 库存量
  %th.action-cell(style="width: 70px;") &nbsp;
%script(id="show-variant-item" type="text/x-handlebars-template")
  =render partial: "admin/product_variants/show"
%script(id="new-variant-item" type="text/x-handlebars-template")
  =render partial: "admin/product_variants/new"
%script(id="variant-options-item" type="text/x-handlebars-template")
  选择:
  %a(href="#" style="color:#000") 所有
  %a(href="#" style="color:#000") 清空
  {{#each_with_index options}}
  %span(class='option-{{index_plus}}')
    {{#each_variant_option ../this index=index_plus}}
    %a(href="#") {{name}}
    {{/each_variant_option}}
  {{/each_with_index}}
%script(id="edit-option-item" type="text/x-handlebars-template")
  %td.cell-title
    .option-selector-frame
      %select.option-selector=options_for_select options
      %input.hide(name="product[options_attributes][][name]" size="16" style="margin-top: 5px;" type="text" value="{{{name}}}")
  %td
    %input(type="hidden" value="0" name="product[options_attributes][][_destroy]")
    %input(type="hidden" value="{{{id}}}" name="product[options_attributes][][id]")
    {{#unless id}}
    %input(type="text" name="product[options_attributes][][value]" size="16" value="{{{value}}}")
    {{/unless}}
    %span.option-value.small {{{variants_option0}}}
    %span.fr.sr(style="margin-top: 5px")
      %a.del-option(href="#" tabindex="-1")
        =image_tag 'admin/icons/trash.gif', alt: '删除', class: [:fr, 'delete-option-link']
      .option-deletemsg.hide
        %p.small.highlight-alt
          {{{name}}}将被删除.
          %a.resume-option(href="#") 恢复
%script(id="show-option-item" type="text/x-handlebars-template")
  %td.cell-title(class="option-{{{position}}}")
    %strong {{{name}}}
  %td.option-values-show.middle.cell-data
    %span.small {{{options}}}
%script(id="product-select-item" type="text/x-handlebars-template")
  %option(value="" style="color: #888") 选择操作&hellip;
  %option.indent(value="price") 修改价格
  %option.indent(value="inventory_quantity") 修改库存量
  %option.indent(disabled="disabled" value="destroy") 删除
  %optgroup(label="复制款式&hellip;")
    {{#each_with_index options}}
    %option(id="dup-option-{{index_plus}}" disabled="disabled" value="duplicate-{{index_plus}}") &hellip;使用另一个{{{item.attributes.name}}}
    {{/each_with_index}}
%script(id="product-image-item" type="text/x-handlebars-template")
  =dialog '{{{title}}}' do
    %img(src="{{{url}}}")

:javascript
  App.init = function(){
    new App.Controllers.Products();
    Backbone.history.start();
  }
  App.product = new App.Models.Product(#{product_json});
  App.product.url = "#{product_path(product)}";
  App.product_variants = new App.Collections.ProductVariants();
  App.product_variants.refresh(#{variants_json});
  App.current_sku_size = #{current_sku_size}
  App.shop_sku_size = #{shop_sku_size}
  new App.Views.Product.Show.Index({model: App.product})

  task_name = 'add_product';